### ISSUE TITLE
removing and setting up aliases is extremely slow

### ISSUE THREAD

**Issue by mjobin-mdsol** [andrewthauer/asdf-alias#11]
**Describe the bug**

Setting up aliases with asdf is a feature I missed from the time I was using rvm
luckily I found your plugin and it seemed to do everything I wanted

Except that it so slow to create and remove aliases, while it should be quasi instant, at least it was with rvm
why is it taking so long?

```
C02C931KLVDL:lyceum majobin$ time asdf alias ruby 3.1.5 --remove

real	1m52.208s
user	0m15.588s
sys	0m50.871s
C02C931KLVDL:lyceum majobin$ time asdf alias ruby 3.1.5 3.1.6
3.1.5 => 3.1.6

real	1m55.978s
user	0m15.844s
sys	0m52.389s
C02C931KLVDL:lyceum majobin$
```

**Steps to reproduce**

create or remove an alias

**Expected behavior**

it should be fast, nearly instant.

**Screenshots**

<img width="529" alt="image" src="https://github.com/user-attachments/assets/bff54896-4bff-439d-bd92-6fb93d832ae1">

**Additional context**

**Comment by mjobin-mdsol** [comment]
I wrote this script to reset my ruby aliases automatically. And unfortunately, it's taking too much time to run

```bash
#!/bin/bash
# https://github.com/andrewthauer/asdf-alias
# asdf plugin add asdf-alias
# or
asdf plugin add alias https://github.com/andrewthauer/asdf-alias.git

asdf_redo_alias() {
  plugin=$1
  latest_rev=$2
  old_revisions=$3

  for cur_revision in $old_revisions
  do
    echo "removing $plugin $cur_revision and aliasing to $latest_rev"
    asdf alias $plugin $cur_revision --remove
    asdf uninstall $plugin $cur_revision
    asdf alias $plugin $cur_revision $latest_rev
  done
}

asdf_redo_alias ruby "3.2.5" "3.2.0 3.2.1 3.2.2 3.2.3 3.2.4"
asdf_redo_alias ruby 3.3.4 "3.3.0 3.3.1 3.3.2 3.3.3"
asdf_redo_alias ruby 3.1.6 "3.1.0 3.1.1 3.1.2 3.1.3 3.1.4 3.1.5"
```

**Comment by andrewthauer** [comment]
My initial guess is that it is related to the `reshim` for the plugin when an alias removed. This is [the function that does this](https://github.com/andrewthauer/asdf-alias/blob/main/lib/commands/command.bash#L122). To test and verify you could commit out the line for the `asdf reshim` call.

The reason a reshim is called when an alias is added and removed is you can run into unknown command issues or other strange behaviour if this is not run.

If it is indeed related to the `reshim`, I would be open to adding an `ASDF_ALIAS_DISABLE_AUTO_RESHIM` environment variable that will disable this. Then for your script you can disable it and run `asdf reshim` at the very end and avoid the hit for each plugin/alias.

**Comment by mjobin-mdsol** [comment]
Thanks for your answer @andrewthauer 

I believe you made a small type, you meant "comment out" and not "commit out", but its okay, I understand. I can test this.

**Comment by mjobin-mdsol** [comment]
Since we had a couple of new rubies lately, I tested the alias with Line 122 commented out
And it was a lot faster.

```
122:  #asdf reshim "$plugin"
```

updated script with latest ruby versions
```
$ cat ~/bin/asdf-redo-alias
#!/bin/bash
# https://github.com/andrewthauer/asdf-alias
# asdf plugin add asdf-alias
# or
asdf plugin add alias https://github.com/andrewthauer/asdf-alias.git

asdf_redo_alias() {
  plugin=$1
  latest_rev=$2
  old_revisions=$3

  for cur_revision in $old_revisions
  do
    echo "removing $plugin $cur_revision and aliasing to $latest_rev"
    asdf alias $plugin $cur_revision --remove
    asdf uninstall $plugin $cur_revision
    asdf alias $plugin $cur_revision $latest_rev
  done
}

asdf_redo_alias ruby 3.2.6 "3.2.0 3.2.1 3.2.2 3.2.3 3.2.4 3.2.5"
asdf_redo_alias ruby 3.3.6 "3.3.0 3.3.1 3.3.2 3.3.3 3.3.4 3.3.5"
asdf_redo_alias ruby 3.1.6 "3.1.0 3.1.1 3.1.2 3.1.3 3.1.4 3.1.5"
```

its kind of fun
