### ISSUE TITLE
Install of the plugin fails if you follow the first instructions

### ISSUE THREAD

**Issue by delgurth** [andrewthauer/asdf-alias#4]
When you try to install this plugin following the first instructions it fails. The plugin is named `alias` in the asdf repository, not `asdf-alias`.

```shell
❯ asdf plugin add asdf-alias
plugin asdf-alias not found in repository
❯ asdf plugin add alias
❯ asdf plugin list --urls --refs
alias                        https://github.com/andrewthauer/asdf-alias.git master b008c47
```

Pull requests #2 fixes this.

**Comment by japhib** [comment]
The second command also fails. I was able to install it directly from the repo by using this:
```
asdf plugin-add alias https://github.com/andrewthauer/asdf-alias.git
```
(The readme currently says `asdf plugin add https://github.com/andrewthauer/asdf-alias.git` which doesn't work)

**Comment by andrewthauer** [comment]
Instructions have been updated.
