### ISSUE TITLE
asdf alias does not work when ASDF_DATA_DIR is not defined

### ISSUE THREAD

**Issue by log2** [andrewthauer/asdf-alias#6]
**Describe the bug**

When ASDF_DATA_DIR is not defined (thus, we are using the default, as defined in https://github.com/asdf-vm/asdf/blob/master/docs/manage/configuration.md#environment-variables), asff alias can't find any plugin.

**Steps to reproduce**

- install asdf, not setting explicitly `ASDF_DATA_DIR` variable
- install asdf alias (`asdf plugin add alias`)
- install asdff java plugin (`asdf plugin add java`), as an example
- launch asdf alias on java plugin (`asdf alias java --auto`)
- message `asdf alias: The plugin 'java' could not be found` is shown and plugin fails

**Expected behavior**

No action is expected from plugin (since no version of java is installed via asdf, yet), but also no error.

**Comment by log2** [comment]
As stated in https://github.com/andrewthauer/asdf-alias/pull/7#pullrequestreview-885590821  , using a library function from asdf, such `asdf_data_dir`, would be better than directly referring the environment variable.

**Comment by andrewthauer** [comment]
Closed by #7
